export { TableHead } from "./TableHead";
export type { ITableHeadProps } from "./TableHead";
export { TableRow } from "./TableRow";
export type { ITableRowProps } from "./TableRow";
export { Th } from "./Th";
export type { IThProps } from "./Th";
export { Td } from "./Td";
export type { ITdProps } from "./Td";
export { Table } from "./Table";
export type { ITableProps } from "./Table";
export { TableBody } from "./TableBody";
export type { ITableBodyProps } from "./TableBody";
